### PR TITLE
(fix) Add Missing Faculty Coordinator 'Nidhi Chandra' Team Photo.

### PR DESCRIPTION
**Pull request by vips28**
Added photo of Faculty coordinator

### CODE REVIEW

**Comment by thisisayush** [comment]
@vips28 Please use a meaningful message for the commit. You can use --ammend flag to modify the last commit message. Also, you are requested to compress the image using compresspng.com in support of the issue #118

**Comment by vips28** [comment]
The optimised image of Nidhi mam has been uploaded.

**Comment by thisisayush** [comment]
@vips28 Please squash the commits to one. Refer to Contribution Guidelines for the same. Also, the commit message seems same `Bug Fix`, please correct that too.

**Comment by thisisayush** [comment]
Thanks for your contribution, @vips28

**Pull request merged**
