### PR TITLE
Fix overflow of Project Card

### LINKED ISSUE #90: Fix Overflow of Project Card
Fix content overflow in project card under Projects.

screenshot_20180314-114536

### PR DESCRIPTION
**Pull request by LevFlavien**
Closes  #90.

Mobile version now shows badges in the same way as desktop version.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Thank you for the PR, can you show a screenshot as this being a more visual
change. Thanks

Best,
Vipul Gupta
@vipulgupta2048

**Comment by thisisayush** [comment]
Hi @levflavien, can you please enable GitHub pages on your repo and share the url? We shall test it before merging.
You can also share the screenshots under different viewport widths.

**Comment by thisisayush** [comment]
There is another PR already open for same issue #119. @vipulgupta2048 Suggestions on what to do?

**Comment by vipulgupta2048** [comment]
I feel, anyone who fixes the issue first would be the most appropriate step
forward.

Best,
Vipul Gupta
@vipulgupta2048

**Comment by LevFlavien** [comment]
Hi, I enabled [GitHub pages](https://levflavien.github.io/asetalias.github.io/showcase.html), but I see the issue has already been resolved.

**Comment by vipulgupta2048** [comment]
No, I hope not. The issue is still ongoing. What helped you make that conclusion?

**Comment by thisisayush** [comment]
Fixed in #119

Thanks for your contribution :)

**Pull request closed without merging**
