### PR TITLE
Making Travis works

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Don't merge yet, need to test by adding Github token.
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
So, why the many commits you ask? 
Travis is a bit difficult to test when you are working on a PR. Next time I will just commit. 

Hopefully, Travis will now run build.py after installing the requirements listed. Hopefully, when successfully, it won't deploy the changes on master branch because that's what happened with us on the blog @swarnimarun @Sc0rpi0n101  

If it does, we can simply switch the deploy tag with after_success tag like everyone does.

**Comment by thisisayush** [comment]
@vipulgupta2048 A PR should contain one logical change, yours contain, Adding "Mr" in front of your name (Seriously? XD), Formatting build file and fixing travis and a lot of commits, squash them, remove changes not applicable for this PR and We're good to go.

**Comment by vipulgupta2048** [comment]
Travis doesn't actually work still. It does everything but deploys to GitHub pages. I will finish this later after 2nd. 
The build.py is formatted automatically and looks pretty good now. Try this formatter called Black.
Change my name for testing purposes only

**Comment by vipulgupta2048** [comment]
Trying something out here. Need some leeway.

**Pull request merged**
