### PR TITLE
website link and name is changed

### PR DESCRIPTION
**Pull request by coderK3**
website link and name is changed in Mozilla Delhi section.

### CODE REVIEW

**Comment by thisisayush** [comment]
@coderK3 We use StaticJinja to build top-level HTML Files, please edit appropriate files and run the build script to re-generate the files.

Files that need to be changed:
- data/communities.json

**Comment by vipulgupta2048** [comment]
Also, @coderK3 refer to which issue you are trying to solve.

**Comment by thisisayush** [comment]
This PR has become obsolete and hence cannot be merged. Please update with latest changes and rebuild using the build script.

@coderK3

**Comment by aniketmaithani** [comment]
Hi Guys, 
Any update on this ?

**Comment by thisisayush** [comment]
Closing this due to inactivity and becoming obsolete.

**Pull request closed without merging**
