### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by foxtrot12**
corrected spelling of "assistance" in about section.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Hi @foxtrot12, thanks for opening this PR. This behavior isn't normal by any means. Travis should have built the website and updated index.html from the last PR that you have made. Keep this open, as I investigate more.

**Comment by thisisayush** [comment]
Nevertheless, this issue was resolved by Travis, so this PR is no longer required. Thank you @foxtrot12 for your contribution. Closing this now.

**Comment by foxtrot12** [comment]
> Nevertheless, this issue was resolved by Travis, so this PR is no longer required. Thank you @foxtrot12 for your contribution. Closing this now.

welcome man, i still didn't get what the issue was 😅

**Comment by thisisayush** [comment]
@foxtrot12 The issue was building top-level HTML Files from templates using the build script before I merged your previous PR Travis was implemented to automate the building process but it failed. So after we fixed Travis this PR is no longer required because this PR contains changes that come after running the build script.

**Pull request closed without merging**
