### PR TITLE
Theme Changed

### PR DESCRIPTION
**Pull request by priyanshu0405**
issue #220 
Changed the templats/prev_events.html file and layout.css files to make the Previous Events page according to the new theme.

- changed the heading with animated underline

-  added two events per line

Screenshot from 2020-08-23 13-54-33

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
Thanks for updating the template, but can you leave the event information as a template variable instead of manually filling it, so that the future events can be easily added. 
And can you try something like https://github.com/asetalias/asetalias.github.io/issues/148#issuecomment-677665555 for the event boxes? 

Also, you don't need to create a new PR for every change, you can just keep updating this one.

**Comment by AbhipsaGuru1012** [comment]
@Sc0rpi0n101 Hey, can I make a PR in this one or I can only suggest ideas?

**Comment by priyanshu0405** [comment]
hey @Sc0rpi0n101, can you please explain "can you leave the event information as a template variable instead of manually filling it", I have updated the event boxes according to #148 (comment).

**Comment by Sc0rpi0n101** [comment]
@AbhipsaGuru1012 you can make a PR about this, but then the work done by @priyanshu0405 will be in vain, as it would do the same thing. So, that would not be right. You can help with reviewing this PR and other suggestions as you like.

**Comment by Sc0rpi0n101** [comment]
> 
> 
> hey @Sc0rpi0n101, can you please explain "can you leave the event information as a template variable instead of manually filling it", I have updated the event boxes according to #148 (comment).

@priyanshu0405 If you look at the file before your changes, the webinar details are parsed using variables like `{{ event.poster }}` etc, while you have added all the details manually. You should keep the event variables as they can take the data directly from the JSON files, and we won't need to update the details on the page manually after every event change. 

Can you also send a screenshot of the updated page?

**Comment by priyanshu0405** [comment]
@Sc0rpi0n101,

2 event boxes in one line would not be possible with the changed format.

asetalias

**Comment by priyanshu0405** [comment]
@Sc0rpi0n101 , I have done the asked worked please have a look.

**Comment by priyanshu0405** [comment]
@Sc0rpi0n101, please take a look.

**Comment by Sc0rpi0n101** [comment]
Hey sorry, I had exams and stuff. 

Can you change the tile size to reduce the width such that we can fit two in a row? Also, increase the height a little bit to make sure the poster are 4:3 height to width as they look kinda skewed rn.

**Comment by priyanshu0405** [comment]
ast

@Sc0rpi0n101, How about this, increasing the height is just increasing the white space and is not looking good.

**Comment by Sc0rpi0n101** [comment]
Can you increase the length of the tiles so that the posters look better? The poster looks skewed now, all the other details look good.

**Comment by fauzank339** [comment]
Can I work on this?

**Comment by Sc0rpi0n101** [comment]
@priyanshu0405 I see there have been no updates for a few months here. Can you please let me know if you can still work on it and finish it?

Otherwise, if you cannot, or if there is no response in 48 hours, @fauzank339, you can continue the work on this.

**Comment by Sc0rpi0n101** [comment]
@fauzank339 so, are you planning to work on this?

**Pull request closed without merging**
