### PR TITLE
Update Upcoming Events Section

### PR DESCRIPTION
**Pull request by vipulgupta2048**
:hatching_chick: Don't merge yet
- Remove bad links #94 
- Will also solve #93 as well.

### CODE REVIEW

**Comment by thisisayush** [comment]
@vipulgupta2048 Any update?

**Comment by vipulgupta2048** [comment]
Damn, I totally forgot what was left to do here :see_no_evil:

**Comment by vipulgupta2048** [comment]
I am done, now. Gotta agree this looks pretty sweet, apart from the crunch of course
Screenshot_2019-11-06_20-28-52
.

**Comment by vipulgupta2048** [comment]
Ready for launch!

**Comment by thisisayush** [comment]
I think we should not add the Thursday Meetups without proper discussion with the current management team, maybe they have other plans and keep it to "No Upcoming Event" for now.

**Comment by vipulgupta2048** [comment]
Well, let me what is the conclusion of that. I feel regular Thursdays help
out a lot to boost retention.

Best,
Vipul Gupta
@vipulgupta2048

**Comment by thisisayush** [comment]
Looping in @vidhigupta9 @SubtleSkills @sjha2048 @Sc0rpi0n101

**Comment by Sc0rpi0n101** [comment]
+2 on Thursday meetups.
As I've been saying we need to be consistent with our events. At least the regular meetups will bring some consistency.

**Comment by sjha2048** [comment]
I agree with @Sc0rpi0n101, consistent thursday meetups are much needed

**Comment by vipulgupta2048** [comment]
@thisisayush Merge when ready. Let's see if the Travis deployment works.

**Pull request merged**
