### PR TITLE
[Update] Fix Issue #94

### PR DESCRIPTION
**Pull request by sanskarv3**
https://github.com/asetalias/asetalias.github.io/issues/94

### CODE REVIEW

**Comment by sanskarv3** [comment]
Done

**Comment by omi10859** [comment]
You need to commit changes and push it again to your fork repo, while working on same branch

**Comment by thisisayush** [comment]
@sanskarv3 Any update on the build?

**Comment by thisisayush** [comment]
@sanskarv3, any update here?

**Comment by thisisayush** [comment]
@sanskarv3 checkout the following wiki to see how to build the website.
https://github.com/asetalias/asetalias.github.io/wiki/Building-the-Website

**Comment by thisisayush** [comment]
Closing due to inactivity.

**Pull request closed without merging**
