### PR TITLE
Update Participate & Learn Section

### PR DESCRIPTION
**Pull request by vipulgupta2048**
The last PR got destroyed, hence reopening.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Solves #98

**Comment by thisisayush** [comment]
I ❤ clean PR's. Merging this now ;)

**Comment by vipulgupta2048** [comment]
Woohooo 200 complete.

**Comment by vipulgupta2048** [comment]
@thisisayush Your misguided love for checking clean PR's has made you blind. 
This is actually taylor swift's "look what you made me do"

This PR's HEAD was probably old or something and you didn't see that this file is actually undoing all the work done I did in PR #187 

How can you be so careless to not see my mistakes? :laughing:

**Pull request merged**
