### PR TITLE
Introducing Cover Page

### PR DESCRIPTION
**Pull request by thisisayush**
Cover Page introduced!
Thanks to Vipul Gupta for idea.

@aniketmaithani Appologies for 7 commits! I tried squashing but being new to GitHub was unable to. Please do guide me for the next steps after this merge on how to do it.

### CODE REVIEW

**Comment by aniketmaithani** [comment]
@thisisayush ref : https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ :) Now this time I'll not merge unless you squash it! :P

**Comment by thisisayush** [comment]
@aniketmaithani I already tried that! There are like errors, warnings, etc. 

If you are free today. Use teamviewer to show me how to do that!  :)

**Comment by aniketmaithani** [comment]
@thisisayush btw a simple google search on how to  resolve merge commit would guide you in right direction. But if you still want, mail me your personal email id :@  maithani.aniket@gmail.com

**Comment by thisisayush** [comment]
Probably 7 pm today or 10pm if possible

**Pull request merged**
