### PR TITLE
feat(volunteers): add ansh-tyagi

### PR DESCRIPTION
**Pull request by anshtyagi0**

### CODE REVIEW

**Comment by jailbreakerVC** [comment]
Reviewing this now, thanks for adding a PR!

**Comment by anshtyagi0** [comment]
@jailbreakerVC Thank you!

**Comment by jailbreakerVC** [comment]
LGTM, merging now. Welcome to ALiAS.

**Comment by anshtyagi0** [comment]
Thank you ❤️

**Pull request merged**
