### PR TITLE
Added a new section/ UI Changes

### PR DESCRIPTION
**Pull request by ATB00ker**
-Made a new css file to keep colors seperately to avoid messy code line in future.
-Introduced a new section called utilities which contains useful links and past event photo boxes.
-Made a new file called functions.js to avoid messy code in data.js file
-UI changes and bug fixes

### CODE REVIEW

**Comment by aniketmaithani** [comment]
@ATB00ker please remove old commit and properly rebase it.

**Comment by ATB00ker** [comment]
I am already working on it!

**Comment by ATB00ker** [comment]
Okay, I have followed instructions online and rebased it,  It is showing 1 commit. Please confirm. Thanks in advance. :)

**Comment by AnimeshVerma17** [comment]
@ATB00ker please resolve the conflicts.

**Comment by aniketmaithani** [comment]
@ATB00ker please look at the master branch. Because I have committed something. Please rebase properly :) Else this PR won't get merged !

**Comment by ATB00ker** [comment]
Sorry for the issue; I rebased it; Another PR must have been accepted after that which i missed. Now it is showing no conflict and has only one commit. 😄

**Comment by thisisayush** [comment]
Waiting for screenshot @ATB00ker

**Comment by ATB00ker** [comment]
Okay. If i am doing that; I'll fix one more bug in this PR and upload screenshot in 10 mins.

**Comment by thisisayush** [comment]
@ATB00ker Also, checked your code. Here are few suggestions:
1. Don't name class as color-1 or color-2 rather give it some meaningful color name for easy usability to other devs too.
2. 'container' is Bootstrap's Class. Add your own class i.e. 'navContainer' alongwith 'container' class to maintain site functionality as it is.
3. Avoid using inline styling! (in preLoader)( a preloader may be used oin multiple pages and may be inserted by using js in future, using inline styling will descrease flexibility and reusability)
4. Too much inline styling used! Prefer to use class or develop a algorithm and apply padding through js
5. Use different icons for favicon, prefer low resolution or compressed ones to reduce load time.
That's All. These are my thoughts after reading your code. All suggestions/improvements/guidance from other devs is welcome and appreciated.

**Comment by ATB00ker** [comment]
alias - google chrome 3_14_2017 6_32_23 pm
alias - google chrome 3_14_2017 6_32_29 pm
alias - google chrome 3_14_2017 6_32_44 pm

**Pull request merged**
