### PR TITLE
Data and UI updates

### PR DESCRIPTION
**Pull request by AnimeshVerma17**
UI updates:
>Added browser tab color for Chrome on Android
>Added gradient background and parallax scrolling effect to home section
>Updated logo image for home section

Data updates:
>Updated list of team members

### CODE REVIEW

**Comment by AnimeshVerma17** [comment]
Will someone please merge this?

**Comment by aniketmaithani** [comment]
Rebase the branch ... and I'll be happy to merge this up :)

**Comment by AnimeshVerma17** [comment]
Ok I am closing this one then...... new PR will be sent just in minutes.

**Comment by aniketmaithani** [comment]
@AnimeshVerma17 correct this PR only! I won't accept the other one :)

**Comment by aniketmaithani** [comment]
@AnimeshVerma17 can you please resolve this conflict :)

**Comment by AnimeshVerma17** [comment]
Resolved 👍

**Comment by thisisayush** [comment]
@AnimeshVerma17 Squash into single commit

**Comment by AnimeshVerma17** [comment]
Well my Git got some serious error so I`m reinstalling it

**Comment by AnimeshVerma17** [comment]
Any idea how to do it via web?

**Pull request merged**
