### PR TITLE
Fixed content overflow of project cards in projects page on mobile screens

### LINKED ISSUE #90: Fix Overflow of Project Card
Fix content overflow in project card under Projects.

screenshot_20180314-114536

### PR DESCRIPTION
**Pull request by AniVerma17**
Resolves #90 .
 - Set height of project cards to `auto` for mobile viewports.

Preview link: https://aniverma17.github.io/asetalias.github.io/showcase.html .

### CODE REVIEW

**Comment by AniVerma17** [comment]
> Hi @AniVerma17, there seem to be a problem on tablet viewport after the fix.
> fireshot capture 3 - alias_ projects showcase_ - https___aniverma17 github io_asetal

Fixed. Check PR.

**Comment by thisisayush** [comment]
Tablet view now seems ok, but there is a overflow scroll in mobile viewport now..

screenshot_20181007-081847
screenshot_20181007-081845

**Comment by thisisayush** [comment]
@AniVerma17 Seems this would be a continuous issue for future projects too. How about using masonry.js and switching to masonry grid layout?

**Comment by thisisayush** [comment]
Expanding cards can be a good option but I don't know if it'll be most apt. option too.

**Comment by AniVerma17** [comment]
> Expanding cards can be a good option but I don't know if it'll be most apt. option too.

I'm gonna do some UX testing on that, if it looks good then will implement it.

**Comment by thisisayush** [comment]
LGTM. Keep us posted.

**Comment by aniketmaithani** [comment]
@thisisayush @Tanya-Jain @AniVerma17 any update on this ?

**Comment by aniketmaithani** [comment]
@thisisayush @Tanya-Jain @AniVerma17 any update on this ?

**Comment by aniketmaithani** [comment]
@thisisayush @Tanya-Jain @AniVerma17 any update on this ?

**Comment by AniVerma17** [comment]
Had been busy, will get back on this soon.

**Comment by thisisayush** [comment]
@AniVerma17 Any Update?

**Comment by AniVerma17** [comment]
> @AniVerma17 Any Update?

Well I tried the expanding effect, but it didn't look as good as expected, mostly because of very less amount of overflowing content. So I'll try other options.

**Comment by thisisayush** [comment]
@AniVerma17 Any update here?

**Comment by AniVerma17** [comment]
> @AniVerma17 Any update here?

I think let's give a shot to staggered layout (masonry), what say?

**Comment by thisisayush** [comment]
@AniVerma17  Sure.

**Comment by vipulgupta2048** [comment]
@AniVerma17 Doing a bit of housekeeping here. Any updates, otherwise we can close and let someone else take up this issue. Thanks!

**Comment by AniVerma17** [comment]
> @AniVerma17 Doing a bit of housekeeping here. Any updates, otherwise we can close and let someone else take up this issue. Thanks!

Yeah I'm back on this now, will update the PR soon.

**Comment by AniVerma17** [comment]
Fixed now for all viewports.
- Sets flexbox layout on cards container for responsiveness.
- Removes fixed height value to fix overflow bug.

Preview available on this [link](https://aniverma17.github.io/asetalias.github.io/showcase.html) .

**Comment by thisisayush** [comment]
The issue seems to be fixed as in preview. Will verify and update.

**Comment by AniVerma17** [comment]
> The issue seems to be fixed as in preview. Will verify and update.

@thisisayush any update?

**Comment by thisisayush** [comment]
@AniVerma17 Can you squash the commits to one? The changes seem to be repeating.

**Comment by AniVerma17** [comment]
> @AniVerma17 Can you squash the commits to one? The changes seem to be repeating.

Done. Check.

**Comment by thisisayush** [comment]
Looks good. Merging.

**Pull request merged**
