### PR TITLE
Frontend Changes

### PR DESCRIPTION
**Pull request by parthsharma2**
Made a few changes in **index.html** and **main.css** to resolve the frontend issues mentioned in [here.](https://github.com/asetalias/asetalias.github.io/issues/9)

### CODE REVIEW

**Comment by aniketmaithani** [comment]
@parthsharma2 can you rebase it. After merging previous PR's it shows your index.html has some merge commit. :) Also if you can squash these commits into single commit that would be great.

**Comment by aniketmaithani** [comment]
@parthsharma2 two things : 
1. First rebase your branch with the master branch of this repo :)
[git rebase ----<> Please Google How to Do it] 
2. Once you are done rebasing and resolving the conflict manually make sure you squash the commit : 

`git squash ....<> rest goes here [Please Google ]`

Following Git Guidelines will keep things simple and clean for the long run. 👍

**Comment by thisisayush** [comment]
@parthsharma2 The repository you updated is old. All the changes you made are already fixed in the current one. :)

**Comment by aniketmaithani** [comment]
I am ignoring this PR. Make a fresh one and rectify the mistakes mentioned.

**Pull request closed without merging**
