### PR TITLE
Feature/communities page

### PR DESCRIPTION
**Pull request by longevitytina**
Restructures communities page as grid layout
Replaces social links with icons
Added logic to include typed header if no logo exists to reduce redundancy
Change background color to match other pages
 
screencapture-0-0-0-0-8000-communities-html-2020-06-04-16_13_50

Co-authored-by: https://github.com/anya-pich <anna.pich@outlook.com >

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
LGTM 
But I'm still not sure mixing Conferences and Communities is a good idea.

We can have two separate sections communities and conferences on this page and add more of each to the sections then. 

CC: @vipulgupta2048 @thisisayush

**Comment by vipulgupta2048** [comment]
Thanks @longevitytina @Sc0rpi0n101 
Yes, I feel we should keep communities and conferences separate. Since conference would also include open-source programs like GSoC and Outreachy. It's basically set up as communities and events (conf + programs)

**Comment by longevitytina** [comment]
Sure, we'll set up two sections under communities page for Conferences and Communities

**Comment by Sc0rpi0n101** [comment]
Closing in favor of #216

**Pull request closed without merging**
