### PR TITLE
Ethical Hacking Event details removed 

### PR DESCRIPTION
**Pull request by saggu10417**
Ethical Hacking Event dated 14 March are removed.
Screenshot from 2019-03-19 13-09-45

### CODE REVIEW

**Comment by thisisayush** [comment]
@saggu10417 this PR consists changes that are proposed in an existing PR, please remove those changes first. This PR should only contain the required changes.

**Comment by saggu10417** [comment]
Sorry i didn't get u ..... Please elaborate

**Comment by saggu10417** [comment]
@thisisayush Help !

**Comment by thisisayush** [comment]
What you did is that you made the changed for previous PR (not merged yet) on master branch and then checked out the new branch for this PR from the same which resulted in adding those commits too in this branch, what you can do is wait for previous PR to get merged and then rebase this branch with master, or I guess cherry picking a single commit on a branch which is even with the master branch of this repo should work too (that would require a new PR or to reset this branch with that branch)

**Comment by thisisayush** [comment]
@saggu10417 Any Update?

**Comment by vipulgupta2048** [comment]
Hello @saggu10417, this PR has become obsolete. Thanks for your contribution, we are closing this for now.

**Pull request closed without merging**
